name: Bug Report
description: Report a bug or issue with AI Team Alpha agents
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us investigate.

  - type: dropdown
    id: agent
    attributes:
      label: Affected Agent
      description: Which agent is experiencing the issue?
      options:
        - Will (Product Owner)
        - Mike (System Architect)  
        - Sarah (Security Architect)
        - Luke (Fullstack Developer)
        - Vijay (QA Engineer)
        - Alex (Infrastructure Engineer)
        - Marcus (Code Reviewer)
        - Diego (Debugger)
        - Elena (Data Scientist)
        - Installation Script
        - Multiple Agents
        - Other/Unknown
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the issue you encountered...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command: claude --agent agent-name "request"
        2. Observe behavior...
        3. Expected vs actual result...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Information about your setup
      placeholder: |
        - OS: (e.g., macOS 14.1, Windows 11, Ubuntu 22.04)
        - Claude Code version: 
        - AI Team Alpha version: 
        - Installation method: (manual, script)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages/Logs
      description: Any error messages or relevant log output
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or screenshots about the problem